//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web365Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArticle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblArticle()
        {
            this.tblGroup_Article_Map = new HashSet<tblGroup_Article_Map>();
            this.tblPicture1 = new HashSet<tblPicture>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string TitleAscii { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> PictureID { get; set; }
        public string Summary { get; set; }
        public string Detail { get; set; }
        public Nullable<int> Viewed { get; set; }
        public string SEOTitle { get; set; }
        public string SEODescription { get; set; }
        public string SEOKeyword { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tblPicture tblPicture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGroup_Article_Map> tblGroup_Article_Map { get; set; }
        public virtual tblTypeArticle tblTypeArticle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPicture> tblPicture1 { get; set; }
    }
}
