//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web365Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual tblGroupOfService tblGroupOfService { get; set; }
    }
}
