//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web365Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblService()
        {
            this.tblGroupOfService = new HashSet<tblGroupOfService>();
            this.tblStepOfService = new HashSet<tblStepOfService>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string TitleAscii { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> Index { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> PictureId { get; set; }
        public Nullable<bool> IsFeartured { get; set; }
        public string SEOTitle { get; set; }
        public string SEODescription { get; set; }
        public string SEOKeyword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGroupOfService> tblGroupOfService { get; set; }
        public virtual tblPicture tblPicture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStepOfService> tblStepOfService { get; set; }
    }
}
